# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/data_dict.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/data_dict.proto',
  package='cn.malgo.algo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15proto/data_dict.proto\x12\rcn.malgo.algo\"w\n\x0b\x43har2IdDict\x12\x38\n\x07\x63harMap\x18\x01 \x03(\x0b\x32\'.cn.malgo.algo.Char2IdDict.CharMapEntry\x1a.\n\x0c\x43harMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x8c\x01\n\x11LabelId2ClassDict\x12\x44\n\nlabelIdMap\x18\x01 \x03(\x0b\x32\x30.cn.malgo.algo.LabelId2ClassDict.LabelIdMapEntry\x1a\x31\n\x0fLabelIdMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_CHAR2IDDICT_CHARMAPENTRY = _descriptor.Descriptor(
  name='CharMapEntry',
  full_name='cn.malgo.algo.Char2IdDict.CharMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cn.malgo.algo.Char2IdDict.CharMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cn.malgo.algo.Char2IdDict.CharMapEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=159,
)

_CHAR2IDDICT = _descriptor.Descriptor(
  name='Char2IdDict',
  full_name='cn.malgo.algo.Char2IdDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='charMap', full_name='cn.malgo.algo.Char2IdDict.charMap', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CHAR2IDDICT_CHARMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=159,
)


_LABELID2CLASSDICT_LABELIDMAPENTRY = _descriptor.Descriptor(
  name='LabelIdMapEntry',
  full_name='cn.malgo.algo.LabelId2ClassDict.LabelIdMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cn.malgo.algo.LabelId2ClassDict.LabelIdMapEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cn.malgo.algo.LabelId2ClassDict.LabelIdMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=302,
)

_LABELID2CLASSDICT = _descriptor.Descriptor(
  name='LabelId2ClassDict',
  full_name='cn.malgo.algo.LabelId2ClassDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labelIdMap', full_name='cn.malgo.algo.LabelId2ClassDict.labelIdMap', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LABELID2CLASSDICT_LABELIDMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=302,
)

_CHAR2IDDICT_CHARMAPENTRY.containing_type = _CHAR2IDDICT
_CHAR2IDDICT.fields_by_name['charMap'].message_type = _CHAR2IDDICT_CHARMAPENTRY
_LABELID2CLASSDICT_LABELIDMAPENTRY.containing_type = _LABELID2CLASSDICT
_LABELID2CLASSDICT.fields_by_name['labelIdMap'].message_type = _LABELID2CLASSDICT_LABELIDMAPENTRY
DESCRIPTOR.message_types_by_name['Char2IdDict'] = _CHAR2IDDICT
DESCRIPTOR.message_types_by_name['LabelId2ClassDict'] = _LABELID2CLASSDICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Char2IdDict = _reflection.GeneratedProtocolMessageType('Char2IdDict', (_message.Message,), dict(

  CharMapEntry = _reflection.GeneratedProtocolMessageType('CharMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _CHAR2IDDICT_CHARMAPENTRY,
    __module__ = 'proto.data_dict_pb2'
    # @@protoc_insertion_point(class_scope:cn.malgo.algo.Char2IdDict.CharMapEntry)
    ))
  ,
  DESCRIPTOR = _CHAR2IDDICT,
  __module__ = 'proto.data_dict_pb2'
  # @@protoc_insertion_point(class_scope:cn.malgo.algo.Char2IdDict)
  ))
_sym_db.RegisterMessage(Char2IdDict)
_sym_db.RegisterMessage(Char2IdDict.CharMapEntry)

LabelId2ClassDict = _reflection.GeneratedProtocolMessageType('LabelId2ClassDict', (_message.Message,), dict(

  LabelIdMapEntry = _reflection.GeneratedProtocolMessageType('LabelIdMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _LABELID2CLASSDICT_LABELIDMAPENTRY,
    __module__ = 'proto.data_dict_pb2'
    # @@protoc_insertion_point(class_scope:cn.malgo.algo.LabelId2ClassDict.LabelIdMapEntry)
    ))
  ,
  DESCRIPTOR = _LABELID2CLASSDICT,
  __module__ = 'proto.data_dict_pb2'
  # @@protoc_insertion_point(class_scope:cn.malgo.algo.LabelId2ClassDict)
  ))
_sym_db.RegisterMessage(LabelId2ClassDict)
_sym_db.RegisterMessage(LabelId2ClassDict.LabelIdMapEntry)


_CHAR2IDDICT_CHARMAPENTRY._options = None
_LABELID2CLASSDICT_LABELIDMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
